export interface CityData {
  slug: string
  name: string
  nameGenitive: string // родительный падеж: "Советска"
  nameDative: string // дательный падеж: "Советску"
  nameAccusative: string // винительный падеж: "Советск"
  namePrepositional: string // предложный падеж: "Советске"
  description: string
  population?: string
  distance?: string
}

export const cities: CityData[] = [
  {
    slug: "sovetsk",
    name: "Советск",
    nameGenitive: "Советска",
    nameDative: "Советску",
    nameAccusative: "Советск",
    namePrepositional: "Советске",
    description: "крупный промышленный город на границе с Литвой",
    population: "40 тыс. человек",
    distance: "120 км от Калининграда",
  },
  {
    slug: "chernyahovsk",
    name: "Черняховск",
    nameGenitive: "Черняховска",
    nameDative: "Черняховску",
    nameAccusative: "Черняховск",
    namePrepositional: "Черняховске",
    description: "важный транспортный узел области",
    population: "36 тыс. человек",
    distance: "85 км от Калининграда",
  },
  {
    slug: "gusev",
    name: "Гусев",
    nameGenitive: "Гусева",
    nameDative: "Гусеву",
    nameAccusative: "Гусев",
    namePrepositional: "Гусеве",
    description: "город с развитой промышленностью",
    population: "28 тыс. человек",
    distance: "110 км от Калининграда",
  },
  {
    slug: "baltiysk",
    name: "Балтийск",
    nameGenitive: "Балтийска",
    nameDative: "Балтийску",
    nameAccusative: "Балтийск",
    namePrepositional: "Балтийске",
    description: "главная военно-морская база Балтийского флота",
    population: "33 тыс. человек",
    distance: "43 км от Калининграда",
  },
  {
    slug: "svetly",
    name: "Светлый",
    nameGenitive: "Светлого",
    nameDative: "Светлому",
    nameAccusative: "Светлый",
    namePrepositional: "Светлом",
    description: "город металлургов на берегу Калининградского залива",
    population: "21 тыс. человек",
    distance: "35 км от Калининграда",
  },
  {
    slug: "zelenogradsk",
    name: "Зеленоградск",
    nameGenitive: "Зеленоградска",
    nameDative: "Зеленоградску",
    nameAccusative: "Зеленоградск",
    namePrepositional: "Зеленоградске",
    description: "популярный курортный город на побережье Балтийского моря",
    population: "16 тыс. человек",
    distance: "32 км от Калининграда",
  },
  {
    slug: "pionersky",
    name: "Пионерский",
    nameGenitive: "Пионерского",
    nameDative: "Пионерскому",
    nameAccusative: "Пионерский",
    namePrepositional: "Пионерском",
    description: "небольшой курортный город на Балтийском побережье",
    population: "11 тыс. человек",
    distance: "45 км от Калининграда",
  },
  {
    slug: "svetlogorsk",
    name: "Светлогорск",
    nameGenitive: "Светлогорска",
    nameDative: "Светлогорску",
    nameAccusative: "Светлогорск",
    namePrepositional: "Светлогорске",
    description: "известный курорт с уникальной архитектурой",
    population: "13 тыс. человек",
    distance: "39 км от Калининграда",
  },
  {
    slug: "gvardeysk",
    name: "Гвардейск",
    nameGenitive: "Гвардейска",
    nameDative: "Гвардейску",
    nameAccusative: "Гвардейск",
    namePrepositional: "Гвардейске",
    description: "районный центр с развитым сельским хозяйством",
    population: "13 тыс. человек",
    distance: "45 км от Калининграда",
  },
  {
    slug: "polessk",
    name: "Полесск",
    nameGenitive: "Полесска",
    nameDative: "Полесску",
    nameAccusative: "Полесск",
    namePrepositional: "Полесске",
    description: "город в центральной части области",
    population: "7 тыс. человек",
    distance: "52 км от Калининграда",
  },
  {
    slug: "slavsk",
    name: "Славск",
    nameGenitive: "Славска",
    nameDative: "Славску",
    nameAccusative: "Славск",
    namePrepositional: "Славске",
    description: "небольшой город в живописной местности",
    population: "4 тыс. человек",
    distance: "120 км от Калининграда",
  },
  {
    slug: "neman",
    name: "Неман",
    nameGenitive: "Немана",
    nameDative: "Неману",
    nameAccusative: "Неман",
    namePrepositional: "Немане",
    description: "город на берегу реки Неман",
    population: "11 тыс. человек",
    distance: "130 км от Калининграда",
  },
  {
    slug: "krasnoznamensk",
    name: "Краснознаменск",
    nameGenitive: "Краснознаменска",
    nameDative: "Краснознаменску",
    nameAccusative: "Краснознаменск",
    namePrepositional: "Краснознаменске",
    description: "город в восточной части области",
    population: "3 тыс. человек",
    distance: "165 км от Калининграда",
  },
  {
    slug: "nesterov",
    name: "Нестеров",
    nameGenitive: "Нестерова",
    nameDative: "Нестерову",
    nameAccusative: "Нестеров",
    namePrepositional: "Нестерове",
    description: "приграничный город с Литвой",
    population: "4 тыс. человек",
    distance: "140 км от Калининграда",
  },
  {
    slug: "ozersk",
    name: "Озёрск",
    nameGenitive: "Озёрска",
    nameDative: "Озёрску",
    nameAccusative: "Озёрск",
    namePrepositional: "Озёрске",
    description: "город среди озёр и лесов",
    population: "5 тыс. человек",
    distance: "130 км от Калининграда",
  },
  {
    slug: "pravdinsk",
    name: "Правдинск",
    nameGenitive: "Правдинска",
    nameDative: "Правдинску",
    nameAccusative: "Правдинск",
    namePrepositional: "Правдинске",
    description: "районный центр с богатой историей",
    population: "4 тыс. человек",
    distance: "65 км от Калининграда",
  },
  {
    slug: "bagrationovsk",
    name: "Багратионовск",
    nameGenitive: "Багратионовска",
    nameDative: "Багратионовску",
    nameAccusative: "Багратионовск",
    namePrepositional: "Багратионовске",
    description: "приграничный город с Польшей",
    population: "6 тыс. человек",
    distance: "37 км от Калининграда",
  },
  {
    slug: "mamonovo",
    name: "Мамоново",
    nameGenitive: "Мамоново",
    nameDative: "Мамоново",
    nameAccusative: "Мамоново",
    namePrepositional: "Мамоново",
    description: "пограничный город на границе с Польшей",
    population: "8 тыс. человек",
    distance: "45 км от Калининграда",
  },
  {
    slug: "ladushkin",
    name: "Ладушкин",
    nameGenitive: "Ладушкина",
    nameDative: "Ладушкину",
    nameAccusative: "Ладушкин",
    namePrepositional: "Ладушкине",
    description: "небольшой город на Калининградском заливе",
    population: "3 тыс. человек",
    distance: "50 км от Калининграда",
  },
  {
    slug: "yantarny",
    name: "Янтарный",
    nameGenitive: "Янтарного",
    nameDative: "Янтарному",
    nameAccusative: "Янтарный",
    namePrepositional: "Янтарном",
    description: "центр янтарной промышленности России",
    population: "5 тыс. человек",
    distance: "48 км от Калининграда",
  },
  {
    slug: "gurievsk",
    name: "Гурьевск",
    nameGenitive: "Гурьевска",
    nameDative: "Гурьевску",
    nameAccusative: "Гурьевск",
    namePrepositional: "Гурьевске",
    description: "город в пригородной зоне Калининграда",
    population: "13 тыс. человек",
    distance: "7 км от Калининграда",
  },
]

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((city) => city.slug === slug)
}

export function getAllCitySlugs(): string[] {
  return cities.map((city) => city.slug)
}
